# netlify.toml for PHPure Docs
[build]
  publish = "dist"
  command = "npm run build"

# Set proper headers for JavaScript chunks to ensure they're properly loaded
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

# Set proper headers for CSS files
[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

# Handle SPA routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Path = {without = ["/assets/**"]}}

# Handle assets directory correctly
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true
